---
- name: Copy systemd unit
  copy:
    src: matching-engine.service
    dest: /etc/systemd/system/matching-engine.service
    mode: "0644"

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable service
  systemd:
    name: matching-engine
    enabled: yes

- name: Start service
  systemd:
    name: matching-engine
    state: restarted
